### ISSUE TITLE
Round 1: Summary of your thoughts

### ISSUE THREAD

**Issue by jonathonbyrdziak** [merchantprotocol/M1-developer-toolbar#4]
I’d like for you to first summarize (just as a simple bullet list is fine) the problems and opportunities you see with regard to the current project. I’ll review this to make sure we’re on the same page, and then you’ll move on to round 2.

**Comment by jonathonbyrdziak** [comment]
Here's the trial brief https://github.com/merchantprotocol/M1-developer-toolbar/wiki/Trial-Brief

**Comment by junaidbhura** [comment]
@Jonathonbyrd Here are my thoughts on the trial brief:

**Questions:**
1. How is this custom wizard interface extension going to be installed on the client's system? Are the clients going to do it themselves, or will this be installed by us?
2. Is the wizard interface going to be a replacement for the Magento Connect Manager?

**My thoughts on the solution**
- I think it would be best to take a peek to see how the Magento Connect Manager (MCM) works under the hood, reverse engineer it, and use it's concepts to built the wizard
- Any package that works on MCM should work on the wizard
- In short, this should be a much easier - and more extensive version of the MCM
- Having a multi-step wizard is definitely useful
- I think it's a big problem for extensions to modify core tables, so it would be best to eliminate this from all extensions unless it's not possible to have functionality without doing so. In my experience so far, I have not come across any functionality which requires modifying core tables. This would make installation and un-installation easy, and more importantly - make our extensions follow the correct Magento pattern of each module having it's own models and tables (ORM) which interact with other core models via extending, JOINs, etc., rather than modify core tables
- If modifying core tables cannot be avoided for some reason (like third party extensions, etc.), maybe we show a list of core tables that are going to be modified? I'd like to re-iterate that this is a bad idea!
- I'm not too sure how we can effectively check for module conflicts during installation - can we discuss this to get more clarity?
- I think one of the settings the wizard should check for is maximum execution time - which can be a potential problem. We could make sure there is ample time available for the wizard to execute to avoid complications
- Perhaps the tool/wizard should take a backup of the database before performing the tasks. If this is not possible, it should strongly recommend that the user does so

**Comment by jonathonbyrdziak** [comment]
1. The custom wizard interface will be a part of this developer toolbar. When people install this developer toolbar on their website, they will then have the ability to see the wizard installation interface.
2. No this will not be a replacement for connect, just another tool to help users install our other extensions. 
   - This really isn't going to have the same functionality as the MCM. My idea with this wizard is that it will be specific to our modules and double check that our modules were installed 100% correct.
   - I know that modifying core tables is a bad idea, but I purchased somebody elses business and this is how he did it.
   - I'm already checking for module conflicts. Please get this repo running locally and check it out.
   - checking for maximum execution time is a great idea.
   - i think taking backups is a great idea. We should extend this module to give us that ability anyway.
